[build]
  base = "DummyProject"
  command = "chmod +x ./gradlew && ./gradlew clean build"
  publish = "."

# Redirects configuration
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/build/docs/javadoc/:splat"
  status = 200
